stages:
  - build
  - test
  - deploy

compile:
  stage: build
  script:
    - make docker-agent

unit test:
  stage: test
  script:
    - docker run --rm --name make_test -v `pwd`:/go/src/github.com/moiot/moha -w /go/src/github.com/moiot/moha golang:1.11.0 make test

integration test:
  stage: test
  script:
    - make integration-test || { tail -n 200 logs/mysql-*.log; exit 1; }
  after_script:
    - make clean-data

release:
  stage: deploy
  variables:
    docker_image: moiot/moha:$CI_COMMIT_TAG
   # latest_image: moiot/moha:latest
  script:
    - make docker-agent
    - docker build -t $docker_image -f ./etc/docker-compose/agent/Dockerfile.production ./etc/docker-compose/agent
    #- docker tag $docker_image $latest_image
    - docker push $docker_image
    #- docker push $latest_image
    - docker image rm $docker_image
    #- docker image rm $latest_image
    - docker image prune -f
  only:
    - tags